name: 'Hello World'
author: 'Oleh Polishchuk'
description: 'Greet someone and record the time'

inputs:
  github-personal-access-token:
    description: 'Token that can be used to access the GitHub API'
    required: true

  atlassian-basic-auth-username:
    description: 'Email as the username for your Atlassian account'
    required: true

  atlassian-basic-auth-password:
    description: 'API token as the password for your Atlassian account'
    required: true

  pattern-to-match:
    description: 'Condition regular expression'
    required: false
    default: 'https:\/\/[a-z]+.atlassian.net\/browse\/(\w{1,4}-\d{1,4})'

  on-success-transition-id:
    description: 'Use this transition id when pattern match'
    required: true

  on-fail-transition-id:
    description: 'User this transition id when pattern does not match'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
